name: PEXProtection
author: "RevivalPMMP"
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
main: RevivalPMMP\PEXProtection\Main
version: 0.1.2
commands:
  pexprotection:
    description: "PEXProtection command"
    usage: "/pexprotection <add|del|world> <args...>"
    aliases: [pexp]
    permission: "pexprotection.command"
permissions:
  pexprotection.command:
    default: op
    description: "Permission to use the PEXProtection command"