name: PEXProtection
author: "RevivalPMMP"
api: [3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1, 4.0.0]
main: RevivalPMMP\PEXProtection\Main
version: 0.1.2
commands:
  pexprotection:
    description: "PEXProtection command"
    usage: "/pexprotection <add|del|world> <args...>"
    aliases: [pexp]
    permission: "pexprotection.command"
permissions:
  pexprotection.command:
    default: op
    description: "Permission to use the PEXProtection command"
